### 3.2.5 异常处理
Koa处理异常的逻辑比较简单，就是简单地打印到控制台。在3.2.1节介绍Koa创建服务的原理时，已经提到了Koa如何做异常处理，这里再看一下callback()函数的实现。
```javascript
callback() {
    const fn = compose(this.middleware);
    // 如果application中监听error事件的个数大于0，则用我们自己的异常监听
    // 否则，执行Koa默认的异常监听逻辑
    if (!this.listenerCount('error')) this.on('error', this.onerror);

    const handleRequest = (req, res) => {
        const ctx = this.createContext(req, res);
        return this.handleRequest(ctx, fn);
    };

    return handleRequest;
}
```
在执行回调函数的时候，Koa会判断一下app上属性listenerCount('error')是否存在，如果存在则执行我们自己定义的error监听逻辑，否则执行Koa默认的error监听逻辑。因为Application类继承Node的Emitter类，所以Application是具有事件监听能力的。

读者如果看了源码，就会发现listenerCount并不是Application类的一个属性。这里需要注意的一点是，Application继承Emitter，就是继承NodeJS.EventEmitter，因为EventEmitter类有静态方法listenerCount()，所以如果我们自己定义app.on('error', (error) => {})，listenerCount会自动加1。

我们再看一下onerror()方法的实现，代码如下。
```javascript
onerror(err) {
    const isNativeError =
        Object.prototype.toString.call(err) === '[object Error]' ||
        err instanceof Error;
    // 如果不是NativeError，则直接抛出异常
    if (!isNativeError) throw new TypeError(util.format('non-error thrown: %j', err));
    // 如果err状态码为404或err.expose为true时，不输出错误
    if (404 === err.status || err.expose) return;
    if (this.silent) return;

    // 直接输出错误栈到控制台
    const msg = err.stack || err.toString();
    console.error(`\n${msg.replace(/^/gm,'')}\n`);
}
```
Koa默认的异常处理确实比较简单，一般在企业里的实际Koa项目中，会自定义一些更完善的异常处理方案。这里举一个具体实例，比如在中间件中有一些异步操作，如果异步操作中有异常，Koa是获取不到错误信息的，看下面的代码。
```javascript
const Koa = require('koa');
const app = new Koa();

app.use(async (ctx, next) => {
    setTimeout(() => {
        throw Error('这里出错了！')
    }, 1000)
    ctx.body = 'hello world';
});

app.listen(4000, () => {
    console.log('server is running, port is 4000')
})
```
中间件中有一个定时器，在1秒后抛出异常，这个异常Koa是捕获不到的，最终导致进程异常退出，这个时候就需要我们自己做一些兜底处理了，比较通用的方法是加一个uncaughtException类型事件的监听，这样就能捕获上述异常了，代码如下。
```javascript
process.on('uncaughtException', (error) => {
    console.log(error)
})
```

### 3.3 Context的核心实现
Context可以理解为上下文，其实就是我们常用的ctx对象。3.2节也介绍了一些上下文相关的知识点，本节主要讲解context.js中的具体实现。

#### 3.3.1 委托机制
context.js中的委托机制使用了一个包delegates。该包是TJ Holowaychuk写的。按照一贯的思维，如果想深入了解delegates的原理，我们要先学会如何使用delegates。先通过一个简单的实例来了解一下delegates能做些什么，代码如下。
```javascript
var delegate = require('delegates');

var obj = {};
obj.request = {
    name: 'liujianhong',
    age: 29,
    sex: '',
    say: function () {
        console.log('hello koa!');
    }
};
// 将obj.request的相关属性委托到obj上，使调用更加简便
delegate(obj,'request')
   .method('say')
   .getter('name')
   .setter('nickname')
   .access('age');

obj.say();
obj.nickname = 'SKHon';
console.log('nickname: ', obj.request.nickname);
console.log('现在年龄：', obj.age);
obj.age = 30;
console.log('明年年龄：', obj.age);
```
首先解释一下链式调用几个方法的含义。
- method：外部对象可以直接调用内部对象的函数。
- getter：外部对象可以直接访问内部对象的值。
- setter：外部对象可以直接修改内部对象的值。 
- access：包含getter与setter的功能。

上述代码的运行结果如图3-3所示。
```
sh-3.2# node index.js
hello koa!
nickname:  SKHon
现在年龄： 29
明年年龄： 30
sh-3.2# 
```
再回过头来看一下代码实现，我们是把obj.request对象上的 
